 const Types = {
    GET_STOCK_QUOTES: "GET_STOCK_QUOTES",
    REQUEST_STOCK_QUOTES: "REQUEST_STOCK_QUOTES",
    GET_STOCK_DETAIL: "GET_STOCK_DETAIL",
    REQUEST_STOCK_QUOTES_ERROR: "REQUEST_STOCK_QUOTES_ERROR",
    GET_STOCK_DETAIL_API_ERROR: "GET_STOCK_DETAIL_API_ERROR",
    SHOW_API_RESPONSE_COUNT: "SHOW_API_RESPONSE_COUNT",
  };
  
  export default Types;